steps:
    - id: download-serviceaccount
      name: gcr.io/cloud-builders/gsutil
      args:
        - cp
        - gs://coterieai-kafka/sa/coterieai-project-2dbda6f3219a.json
        - .
    - id: coterieai-api-build
      name: gcr.io/cloud-builders/docker
      args:
        - build
        - --tag=gcr.io/${PROJECT_ID}/${BRANCH_NAME}/coterieai-api:1.0.0
        - .
      wait_for:
        - download-serviceaccount
    - id: coterieai-api-packaging
      name: gcr.io/cloud-builders/docker
      args:
        - push
        - gcr.io/${PROJECT_ID}/${BRANCH_NAME}/coterieai-api:1.0.0
      waitFor:
        - coterieai-api-build
    - id: coterieai-api-cloudrun
      name: gcr.io/cloud-builders/gcloud
      args:
        - run
        - deploy
        - coterieai-api-${BRANCH_NAME}
        - --image
        - gcr.io/${PROJECT_ID}/${BRANCH_NAME}/coterieai-api:1.0.0
        - --port
        - "8000"
        - --region
        - us-central1
        - --platform
        - managed
        - --allow-unauthenticated
        - --memory
        - 1028Mi
      wait_for:
        - coterieai-api-packaging