# Generated by Django 3.1.7 on 2021-03-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210224_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=600)),
                ('author', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.CharField(max_length=600)),
                ('tag_name', models.CharField(max_length=600)),
                ('tag_commit_sha', models.CharField(max_length=600)),
                ('release_name', models.CharField(max_length=600)),
                ('publish_date', models.CharField(max_length=600)),
                ('bucket', models.CharField(max_length=600)),
                ('model_name', models.CharField(max_length=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
