# Generated by Django 3.1.7 on 2021-03-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_aimodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='bucket',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='release_name',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='sha',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='tag_commit_sha',
        ),
        migrations.RemoveField(
            model_name='aimodel',
            name='tag_name',
        ),
        migrations.AddField(
            model_name='aimodel',
            name='gcr_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
