# Generated by Django 3.1.7 on 2021-03-25 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_deployment'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='model',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='api.aimodel'),
            preserve_default=False,
        ),
    ]
