# Generated by Django 3.1.7 on 2021-03-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_deployment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='service_endpoint',
            field=models.URLField(blank=True, default=''),
        ),
    ]
