# Generated by Django 3.1.7 on 2021-03-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_deployment_service_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='deployment_id',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
