# Generated by Django 3.1.7 on 2021-03-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210327_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='gcr_url',
            field=models.URLField(),
        ),
    ]
