apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: coterieai-apihub
  name: coterieai-apihub
  namespace: coteriehubs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coterieai-apihub
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: coterieai-apihub
    spec:
      containers:
        - image: coterieaihub-gitops
          imagePullPolicy: IfNotPresent
          name: coterieaihub-gitops
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: coterieai-apihub
  namespace: coteriehubs
spec:
  maxReplicas: 3
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: coterieai-apihub
