apiVersion: v1
kind: Service
metadata:
  name: coterieai-apihub-service
  namespace: coteriehub
  labels:
    app: coterieai-apihub
    kustomize.toolkit.fluxcd.io/checksum: 262afae7c513df48cec2c0fc82d5da53788dc11b
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
spec:
  ports:
  - port: 8000
    name: http
  selector:
    app: coterieai-apihub
